/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as Layout403RouteImport } from './routes/_layout/403'
import { Route as LayoutDevRouteImport } from './routes/_layout/dev'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutRolesRouteImport } from './routes/_layout/roles'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutRolesIndexRouteImport } from './routes/_layout/roles/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutSettingsNotificationsRouteImport } from './routes/_layout/settings/notifications'
import { Route as LayoutSettingsProfileRouteImport } from './routes/_layout/settings/profile'
import { Route as LayoutSettingsSecurityRouteImport } from './routes/_layout/settings/security'
import { Route as LayoutSystemAuditLogsRouteImport } from './routes/_layout/system/audit-logs'
import { Route as LayoutSystemSettingsRouteImport } from './routes/_layout/system/settings'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutUsersNewRouteImport } from './routes/_layout/users/new'
import { Route as LayoutProjectsIdAssetsRouteImport } from './routes/_layout/projects/$id/assets'
import { Route as LayoutProjectsIdContentTypesRouteImport } from './routes/_layout/projects/$id/content-types'
import { Route as LayoutProjectsIdContentsRouteImport } from './routes/_layout/projects/$id/contents'
import { Route as LayoutProjectsIdOverviewRouteImport } from './routes/_layout/projects/$id/overview'
import { Route as LayoutSystemAuditLogsIndexRouteImport } from './routes/_layout/system/audit-logs/index'
import { Route as LayoutSystemAuditLogsIdRouteImport } from './routes/_layout/system/audit-logs/$id'
import { Route as LayoutUsersIdIndexRouteImport } from './routes/_layout/users/$id/index'
import { Route as LayoutUsersIdEditRouteImport } from './routes/_layout/users/$id/edit'
import { Route as LayoutProjectsIdContentTypesIndexRouteImport } from './routes/_layout/projects/$id/content-types/index'
import { Route as LayoutProjectsIdContentTypesNewRouteImport } from './routes/_layout/projects/$id/content-types/new'
import { Route as LayoutProjectsIdContentsIndexRouteImport } from './routes/_layout/projects/$id/contents/index'
import { Route as LayoutProjectsIdContentTypesIdIndexRouteImport } from './routes/_layout/projects/$id/content-types/$id/index'
import { Route as LayoutProjectsIdContentTypesIdEditRouteImport } from './routes/_layout/projects/$id/content-types/$id/edit'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const Layout403Route = Layout403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevRoute = LayoutDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRolesRoute = LayoutRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutRolesIndexRoute = LayoutRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRolesRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsNotificationsRoute =
  LayoutSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsProfileRoute = LayoutSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsSecurityRoute = LayoutSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSystemAuditLogsRoute = LayoutSystemAuditLogsRouteImport.update({
  id: '/system/audit-logs',
  path: '/system/audit-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemSettingsRoute = LayoutSystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutUsersNewRoute = LayoutUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutProjectsIdAssetsRoute = LayoutProjectsIdAssetsRouteImport.update({
  id: '/$id/assets',
  path: '/$id/assets',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsIdContentTypesRoute =
  LayoutProjectsIdContentTypesRouteImport.update({
    id: '/$id/content-types',
    path: '/$id/content-types',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsIdContentsRoute =
  LayoutProjectsIdContentsRouteImport.update({
    id: '/$id/contents',
    path: '/$id/contents',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutProjectsIdOverviewRoute =
  LayoutProjectsIdOverviewRouteImport.update({
    id: '/$id/overview',
    path: '/$id/overview',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutSystemAuditLogsIndexRoute =
  LayoutSystemAuditLogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutSystemAuditLogsRoute,
  } as any)
const LayoutSystemAuditLogsIdRoute = LayoutSystemAuditLogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutSystemAuditLogsRoute,
} as any)
const LayoutUsersIdIndexRoute = LayoutUsersIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutUsersIdEditRoute = LayoutUsersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutProjectsIdContentTypesIndexRoute =
  LayoutProjectsIdContentTypesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProjectsIdContentTypesRoute,
  } as any)
const LayoutProjectsIdContentTypesNewRoute =
  LayoutProjectsIdContentTypesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LayoutProjectsIdContentTypesRoute,
  } as any)
const LayoutProjectsIdContentsIndexRoute =
  LayoutProjectsIdContentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProjectsIdContentsRoute,
  } as any)
const LayoutProjectsIdContentTypesIdIndexRoute =
  LayoutProjectsIdContentTypesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => LayoutProjectsIdContentTypesRoute,
  } as any)
const LayoutProjectsIdContentTypesIdEditRoute =
  LayoutProjectsIdContentTypesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => LayoutProjectsIdContentTypesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/403': typeof Layout403Route
  '/dev': typeof LayoutDevRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/roles': typeof LayoutRolesRouteWithChildren
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/users': typeof LayoutUsersRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/settings/notifications': typeof LayoutSettingsNotificationsRoute
  '/settings/profile': typeof LayoutSettingsProfileRoute
  '/settings/security': typeof LayoutSettingsSecurityRoute
  '/system/audit-logs': typeof LayoutSystemAuditLogsRouteWithChildren
  '/system/settings': typeof LayoutSystemSettingsRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/roles/': typeof LayoutRolesIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
  '/projects/$id/assets': typeof LayoutProjectsIdAssetsRoute
  '/projects/$id/content-types': typeof LayoutProjectsIdContentTypesRouteWithChildren
  '/projects/$id/contents': typeof LayoutProjectsIdContentsRouteWithChildren
  '/projects/$id/overview': typeof LayoutProjectsIdOverviewRoute
  '/system/audit-logs/$id': typeof LayoutSystemAuditLogsIdRoute
  '/users/$id/edit': typeof LayoutUsersIdEditRoute
  '/system/audit-logs/': typeof LayoutSystemAuditLogsIndexRoute
  '/users/$id/': typeof LayoutUsersIdIndexRoute
  '/projects/$id/content-types/new': typeof LayoutProjectsIdContentTypesNewRoute
  '/projects/$id/content-types/': typeof LayoutProjectsIdContentTypesIndexRoute
  '/projects/$id/contents/': typeof LayoutProjectsIdContentsIndexRoute
  '/projects/$id/content-types/$id/edit': typeof LayoutProjectsIdContentTypesIdEditRoute
  '/projects/$id/content-types/$id/': typeof LayoutProjectsIdContentTypesIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/403': typeof Layout403Route
  '/dev': typeof LayoutDevRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof LayoutIndexRoute
  '/settings/notifications': typeof LayoutSettingsNotificationsRoute
  '/settings/profile': typeof LayoutSettingsProfileRoute
  '/settings/security': typeof LayoutSettingsSecurityRoute
  '/system/settings': typeof LayoutSystemSettingsRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/roles': typeof LayoutRolesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/projects/$id/assets': typeof LayoutProjectsIdAssetsRoute
  '/projects/$id/overview': typeof LayoutProjectsIdOverviewRoute
  '/system/audit-logs/$id': typeof LayoutSystemAuditLogsIdRoute
  '/users/$id/edit': typeof LayoutUsersIdEditRoute
  '/system/audit-logs': typeof LayoutSystemAuditLogsIndexRoute
  '/users/$id': typeof LayoutUsersIdIndexRoute
  '/projects/$id/content-types/new': typeof LayoutProjectsIdContentTypesNewRoute
  '/projects/$id/content-types': typeof LayoutProjectsIdContentTypesIndexRoute
  '/projects/$id/contents': typeof LayoutProjectsIdContentsIndexRoute
  '/projects/$id/content-types/$id/edit': typeof LayoutProjectsIdContentTypesIdEditRoute
  '/projects/$id/content-types/$id': typeof LayoutProjectsIdContentTypesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_layout/403': typeof Layout403Route
  '/_layout/dev': typeof LayoutDevRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/roles': typeof LayoutRolesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/users': typeof LayoutUsersRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/settings/notifications': typeof LayoutSettingsNotificationsRoute
  '/_layout/settings/profile': typeof LayoutSettingsProfileRoute
  '/_layout/settings/security': typeof LayoutSettingsSecurityRoute
  '/_layout/system/audit-logs': typeof LayoutSystemAuditLogsRouteWithChildren
  '/_layout/system/settings': typeof LayoutSystemSettingsRoute
  '/_layout/users/new': typeof LayoutUsersNewRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/roles/': typeof LayoutRolesIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/projects/$id/assets': typeof LayoutProjectsIdAssetsRoute
  '/_layout/projects/$id/content-types': typeof LayoutProjectsIdContentTypesRouteWithChildren
  '/_layout/projects/$id/contents': typeof LayoutProjectsIdContentsRouteWithChildren
  '/_layout/projects/$id/overview': typeof LayoutProjectsIdOverviewRoute
  '/_layout/system/audit-logs/$id': typeof LayoutSystemAuditLogsIdRoute
  '/_layout/users/$id/edit': typeof LayoutUsersIdEditRoute
  '/_layout/system/audit-logs/': typeof LayoutSystemAuditLogsIndexRoute
  '/_layout/users/$id/': typeof LayoutUsersIdIndexRoute
  '/_layout/projects/$id/content-types/new': typeof LayoutProjectsIdContentTypesNewRoute
  '/_layout/projects/$id/content-types/': typeof LayoutProjectsIdContentTypesIndexRoute
  '/_layout/projects/$id/contents/': typeof LayoutProjectsIdContentsIndexRoute
  '/_layout/projects/$id/content-types/$id/edit': typeof LayoutProjectsIdContentTypesIdEditRoute
  '/_layout/projects/$id/content-types/$id/': typeof LayoutProjectsIdContentTypesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/403'
    | '/dev'
    | '/projects'
    | '/roles'
    | '/settings'
    | '/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/system/audit-logs'
    | '/system/settings'
    | '/users/new'
    | '/projects/'
    | '/roles/'
    | '/settings/'
    | '/users/'
    | '/projects/$id/assets'
    | '/projects/$id/content-types'
    | '/projects/$id/contents'
    | '/projects/$id/overview'
    | '/system/audit-logs/$id'
    | '/users/$id/edit'
    | '/system/audit-logs/'
    | '/users/$id/'
    | '/projects/$id/content-types/new'
    | '/projects/$id/content-types/'
    | '/projects/$id/contents/'
    | '/projects/$id/content-types/$id/edit'
    | '/projects/$id/content-types/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/403'
    | '/dev'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/system/settings'
    | '/users/new'
    | '/projects'
    | '/roles'
    | '/settings'
    | '/users'
    | '/projects/$id/assets'
    | '/projects/$id/overview'
    | '/system/audit-logs/$id'
    | '/users/$id/edit'
    | '/system/audit-logs'
    | '/users/$id'
    | '/projects/$id/content-types/new'
    | '/projects/$id/content-types'
    | '/projects/$id/contents'
    | '/projects/$id/content-types/$id/edit'
    | '/projects/$id/content-types/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/_layout/403'
    | '/_layout/dev'
    | '/_layout/projects'
    | '/_layout/roles'
    | '/_layout/settings'
    | '/_layout/users'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/_layout/'
    | '/_layout/settings/notifications'
    | '/_layout/settings/profile'
    | '/_layout/settings/security'
    | '/_layout/system/audit-logs'
    | '/_layout/system/settings'
    | '/_layout/users/new'
    | '/_layout/projects/'
    | '/_layout/roles/'
    | '/_layout/settings/'
    | '/_layout/users/'
    | '/_layout/projects/$id/assets'
    | '/_layout/projects/$id/content-types'
    | '/_layout/projects/$id/contents'
    | '/_layout/projects/$id/overview'
    | '/_layout/system/audit-logs/$id'
    | '/_layout/users/$id/edit'
    | '/_layout/system/audit-logs/'
    | '/_layout/users/$id/'
    | '/_layout/projects/$id/content-types/new'
    | '/_layout/projects/$id/content-types/'
    | '/_layout/projects/$id/contents/'
    | '/_layout/projects/$id/content-types/$id/edit'
    | '/_layout/projects/$id/content-types/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/403': {
      id: '/_layout/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Layout403RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dev': {
      id: '/_layout/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof LayoutDevRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roles': {
      id: '/_layout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof LayoutRolesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/roles/': {
      id: '/_layout/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof LayoutRolesIndexRouteImport
      parentRoute: typeof LayoutRolesRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/notifications': {
      id: '/_layout/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof LayoutSettingsNotificationsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/profile': {
      id: '/_layout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutSettingsProfileRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/security': {
      id: '/_layout/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutSettingsSecurityRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/system/audit-logs': {
      id: '/_layout/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof LayoutSystemAuditLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/settings': {
      id: '/_layout/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof LayoutSystemSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/users/new': {
      id: '/_layout/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof LayoutUsersNewRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/projects/$id/assets': {
      id: '/_layout/projects/$id/assets'
      path: '/$id/assets'
      fullPath: '/projects/$id/assets'
      preLoaderRoute: typeof LayoutProjectsIdAssetsRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$id/content-types': {
      id: '/_layout/projects/$id/content-types'
      path: '/$id/content-types'
      fullPath: '/projects/$id/content-types'
      preLoaderRoute: typeof LayoutProjectsIdContentTypesRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$id/contents': {
      id: '/_layout/projects/$id/contents'
      path: '/$id/contents'
      fullPath: '/projects/$id/contents'
      preLoaderRoute: typeof LayoutProjectsIdContentsRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$id/overview': {
      id: '/_layout/projects/$id/overview'
      path: '/$id/overview'
      fullPath: '/projects/$id/overview'
      preLoaderRoute: typeof LayoutProjectsIdOverviewRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/system/audit-logs/': {
      id: '/_layout/system/audit-logs/'
      path: '/'
      fullPath: '/system/audit-logs/'
      preLoaderRoute: typeof LayoutSystemAuditLogsIndexRouteImport
      parentRoute: typeof LayoutSystemAuditLogsRoute
    }
    '/_layout/system/audit-logs/$id': {
      id: '/_layout/system/audit-logs/$id'
      path: '/$id'
      fullPath: '/system/audit-logs/$id'
      preLoaderRoute: typeof LayoutSystemAuditLogsIdRouteImport
      parentRoute: typeof LayoutSystemAuditLogsRoute
    }
    '/_layout/users/$id/': {
      id: '/_layout/users/$id/'
      path: '/$id'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof LayoutUsersIdIndexRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/users/$id/edit': {
      id: '/_layout/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof LayoutUsersIdEditRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/projects/$id/content-types/': {
      id: '/_layout/projects/$id/content-types/'
      path: '/'
      fullPath: '/projects/$id/content-types/'
      preLoaderRoute: typeof LayoutProjectsIdContentTypesIndexRouteImport
      parentRoute: typeof LayoutProjectsIdContentTypesRoute
    }
    '/_layout/projects/$id/content-types/new': {
      id: '/_layout/projects/$id/content-types/new'
      path: '/new'
      fullPath: '/projects/$id/content-types/new'
      preLoaderRoute: typeof LayoutProjectsIdContentTypesNewRouteImport
      parentRoute: typeof LayoutProjectsIdContentTypesRoute
    }
    '/_layout/projects/$id/contents/': {
      id: '/_layout/projects/$id/contents/'
      path: '/'
      fullPath: '/projects/$id/contents/'
      preLoaderRoute: typeof LayoutProjectsIdContentsIndexRouteImport
      parentRoute: typeof LayoutProjectsIdContentsRoute
    }
    '/_layout/projects/$id/content-types/$id/': {
      id: '/_layout/projects/$id/content-types/$id/'
      path: '/$id'
      fullPath: '/projects/$id/content-types/$id/'
      preLoaderRoute: typeof LayoutProjectsIdContentTypesIdIndexRouteImport
      parentRoute: typeof LayoutProjectsIdContentTypesRoute
    }
    '/_layout/projects/$id/content-types/$id/edit': {
      id: '/_layout/projects/$id/content-types/$id/edit'
      path: '/$id/edit'
      fullPath: '/projects/$id/content-types/$id/edit'
      preLoaderRoute: typeof LayoutProjectsIdContentTypesIdEditRouteImport
      parentRoute: typeof LayoutProjectsIdContentTypesRoute
    }
  }
}

interface LayoutProjectsIdContentTypesRouteChildren {
  LayoutProjectsIdContentTypesNewRoute: typeof LayoutProjectsIdContentTypesNewRoute
  LayoutProjectsIdContentTypesIndexRoute: typeof LayoutProjectsIdContentTypesIndexRoute
  LayoutProjectsIdContentTypesIdEditRoute: typeof LayoutProjectsIdContentTypesIdEditRoute
  LayoutProjectsIdContentTypesIdIndexRoute: typeof LayoutProjectsIdContentTypesIdIndexRoute
}

const LayoutProjectsIdContentTypesRouteChildren: LayoutProjectsIdContentTypesRouteChildren =
  {
    LayoutProjectsIdContentTypesNewRoute: LayoutProjectsIdContentTypesNewRoute,
    LayoutProjectsIdContentTypesIndexRoute:
      LayoutProjectsIdContentTypesIndexRoute,
    LayoutProjectsIdContentTypesIdEditRoute:
      LayoutProjectsIdContentTypesIdEditRoute,
    LayoutProjectsIdContentTypesIdIndexRoute:
      LayoutProjectsIdContentTypesIdIndexRoute,
  }

const LayoutProjectsIdContentTypesRouteWithChildren =
  LayoutProjectsIdContentTypesRoute._addFileChildren(
    LayoutProjectsIdContentTypesRouteChildren,
  )

interface LayoutProjectsIdContentsRouteChildren {
  LayoutProjectsIdContentsIndexRoute: typeof LayoutProjectsIdContentsIndexRoute
}

const LayoutProjectsIdContentsRouteChildren: LayoutProjectsIdContentsRouteChildren =
  {
    LayoutProjectsIdContentsIndexRoute: LayoutProjectsIdContentsIndexRoute,
  }

const LayoutProjectsIdContentsRouteWithChildren =
  LayoutProjectsIdContentsRoute._addFileChildren(
    LayoutProjectsIdContentsRouteChildren,
  )

interface LayoutProjectsRouteChildren {
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutProjectsIdAssetsRoute: typeof LayoutProjectsIdAssetsRoute
  LayoutProjectsIdContentTypesRoute: typeof LayoutProjectsIdContentTypesRouteWithChildren
  LayoutProjectsIdContentsRoute: typeof LayoutProjectsIdContentsRouteWithChildren
  LayoutProjectsIdOverviewRoute: typeof LayoutProjectsIdOverviewRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutProjectsIdAssetsRoute: LayoutProjectsIdAssetsRoute,
  LayoutProjectsIdContentTypesRoute:
    LayoutProjectsIdContentTypesRouteWithChildren,
  LayoutProjectsIdContentsRoute: LayoutProjectsIdContentsRouteWithChildren,
  LayoutProjectsIdOverviewRoute: LayoutProjectsIdOverviewRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRolesRouteChildren {
  LayoutRolesIndexRoute: typeof LayoutRolesIndexRoute
}

const LayoutRolesRouteChildren: LayoutRolesRouteChildren = {
  LayoutRolesIndexRoute: LayoutRolesIndexRoute,
}

const LayoutRolesRouteWithChildren = LayoutRolesRoute._addFileChildren(
  LayoutRolesRouteChildren,
)

interface LayoutSettingsRouteChildren {
  LayoutSettingsNotificationsRoute: typeof LayoutSettingsNotificationsRoute
  LayoutSettingsProfileRoute: typeof LayoutSettingsProfileRoute
  LayoutSettingsSecurityRoute: typeof LayoutSettingsSecurityRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsNotificationsRoute: LayoutSettingsNotificationsRoute,
  LayoutSettingsProfileRoute: LayoutSettingsProfileRoute,
  LayoutSettingsSecurityRoute: LayoutSettingsSecurityRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutUsersRouteChildren {
  LayoutUsersNewRoute: typeof LayoutUsersNewRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutUsersIdEditRoute: typeof LayoutUsersIdEditRoute
  LayoutUsersIdIndexRoute: typeof LayoutUsersIdIndexRoute
}

const LayoutUsersRouteChildren: LayoutUsersRouteChildren = {
  LayoutUsersNewRoute: LayoutUsersNewRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutUsersIdEditRoute: LayoutUsersIdEditRoute,
  LayoutUsersIdIndexRoute: LayoutUsersIdIndexRoute,
}

const LayoutUsersRouteWithChildren = LayoutUsersRoute._addFileChildren(
  LayoutUsersRouteChildren,
)

interface LayoutSystemAuditLogsRouteChildren {
  LayoutSystemAuditLogsIdRoute: typeof LayoutSystemAuditLogsIdRoute
  LayoutSystemAuditLogsIndexRoute: typeof LayoutSystemAuditLogsIndexRoute
}

const LayoutSystemAuditLogsRouteChildren: LayoutSystemAuditLogsRouteChildren = {
  LayoutSystemAuditLogsIdRoute: LayoutSystemAuditLogsIdRoute,
  LayoutSystemAuditLogsIndexRoute: LayoutSystemAuditLogsIndexRoute,
}

const LayoutSystemAuditLogsRouteWithChildren =
  LayoutSystemAuditLogsRoute._addFileChildren(
    LayoutSystemAuditLogsRouteChildren,
  )

interface LayoutRouteChildren {
  Layout403Route: typeof Layout403Route
  LayoutDevRoute: typeof LayoutDevRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutRolesRoute: typeof LayoutRolesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutUsersRoute: typeof LayoutUsersRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSystemAuditLogsRoute: typeof LayoutSystemAuditLogsRouteWithChildren
  LayoutSystemSettingsRoute: typeof LayoutSystemSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  Layout403Route: Layout403Route,
  LayoutDevRoute: LayoutDevRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutRolesRoute: LayoutRolesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutUsersRoute: LayoutUsersRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSystemAuditLogsRoute: LayoutSystemAuditLogsRouteWithChildren,
  LayoutSystemSettingsRoute: LayoutSystemSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
